### ISSUE TITLE
Add support for #[deny(missing_docs)]?

### ISSUE THREAD

**Issue by grantspassoregon** [Lymia/derive_setters#10]
For our CI, it is common to deny commits based on unresolved clippy warnings.  For more mature projects, we will add #[warn(missing_docs)] to the top of the module.  If I use Setters to derive setters for a struct, this produces a documentation warning that I cannot easily address.

<img width="890" alt="image" src="https://github.com/user-attachments/assets/b6c5e0c4-dbd8-423b-945c-00b11ec9dc41">

From a related issue on the bytemuck crate discussed on [URLO](https://users.rust-lang.org/t/suppress-missing-doc-error-resulting-from-a-derive-macro/97301), one recommendation given was:
> You could open an issue on the bytemuck repo asking the derive macro to include #[allow(missing_docs)] on the generated struct too.

Perhaps setters are generalizable such that inserting a relatively generic "Sets the value of [x] field to [arg]" as a doc comment would work as well.

Thank you,
Erik

**Comment by grantspassoregon** [comment]
Experimenting a bit more, I note that if I document the private fields being accessed by the setter, it clears the warning, but this is not a total win, because it duplicates the doc comment describing the field in the setter method:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/24ac2ac0-ed17-4613-8748-47f381b7f67d">

<img width="515" alt="image" src="https://github.com/user-attachments/assets/9a983f94-fb4b-42dd-b04e-9721a16582ba">

I can imagine writing a good doc comment for one method, or the other, but not as easily for both at once.  Am I using this as intended?

**Comment by Lymia** [comment]
I'll think about this use case. derive_getters and derive_new are by other authors, and I had not expected that this would be a possible issue when I first wrote this.

**Comment by grantspassoregon** [comment]
Thank you, Rimi.

I checked out the changes this morning, and this seems to work like a charm for our use case.

Much appreciated.
Erik



[cid:2812831a-aed7-48cf-96a9-f77fdafe8e77]

________________________________
